name: Lint and test
on: 
  push:
    branches-ignore: main
jobs:
  lint-test:  
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/workflows/test-lint-reusable
        with:
          installCommand: npm i

