name: Lint and test
on: 
  push:
    branches-ignore: main
jobs:
  lint-test:  
    runs-on: ubuntu-latest
    steps:
      - uses: jlangy/vue-3-nginx/.github/workflows/test-lint-reusable.yaml@main
        with:
          installCommand: npm i

