name: Release Version
on: [ workflow_dispatch ]

jobs:
  version-bump:
    name:  'Automated Version Bump'
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout source code'
        uses: 'actions/checkout@v2'
        with:
          ref: ${{ github.ref }}

      - name: 'Automated Version Bump'  
        uses:  'phips28/gh-action-bump-version@master'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build:
    name:  'Run Openshift Build'
    runs-on: ubuntu-latest

    steps:
      - name: Authenticate and set context
        uses: redhat-actions/oc-login@v1
        env:
          OPENSHIFT_USER: jlangy2
          OPENSHIFT_NAMESPACE: jlangy2-dev

        with:
          openshift_server_url: ${{ secrets.OPENSHIFT_SERVER }}
          openshift_token: ${{ secrets.OPENSHIFT_TOKEN }}

          # Disables SSL cert checking. Use this if you don't have the certificate authority data.
          # insecure_skip_tls_verify: true
          # This method is more secure, if the certificate from Step 4 is available.
          # certificate_authority_data: ${{ secrets.CA_DATA }}
          namespace: ${{ env.OPENSHIFT_NAMESPACE }}
      
      - name: build-image
        run: |
          oc status