name: Release Version
on: 
  workflow_dispatch:
  release:
    types: [published]
  # push:
  #   branches: main

jobs:
  echo-tag:
    runs-on: ubuntu-latest
    steps:
      - name: echo tag
        run: |
          echo ${{ github.event.release.tag_name }}

  build:
    name:  'Run Openshift Build'
    runs-on: ubuntu-latest
    steps:
      - name: Authenticate and set context
        uses: redhat-actions/oc-login@v1
        env:
          OPENSHIFT_USER: jlangy2
          OPENSHIFT_NAMESPACE: jlangy2-dev

        with:
          openshift_server_url: ${{ secrets.OPENSHIFT_SERVER }}
          openshift_token: ${{ secrets.OPENSHIFT_TOKEN }}
          namespace: ${{ env.OPENSHIFT_NAMESPACE }}
      
      - name: build-image
        run: |
          oc version
          oc start-build vue-3 --follow
          oc tag jons-vue-3:latest jons-vue-3:${{ github.event.release.tag_name }}
          oc set image deploy/vue-3 vue-3=${{REGISTRY_URL}}/jons-vue-3:${{ github.event.release.tag_name }}
