name: Release Version
on: 
  workflow_dispatch:
  push:
    branches: main


jobs:
  version-bump:
    name:  'Automated Version Bump'
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout source code'
        uses: 'actions/checkout@v2'
        with:
          ref: ${{ github.ref }}

      - name: 'Automated Version Bump'  
        uses:  'phips28/gh-action-bump-version@master'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build:
    name:  'Run Openshift Build'
    runs-on: ubuntu-latest
    needs: version-bump
    steps:
      - name: Authenticate and set context
        uses: redhat-actions/oc-login@v1
        env:
          OPENSHIFT_USER: jlangy2
          OPENSHIFT_NAMESPACE: jlangy2-dev

        with:
          openshift_server_url: ${{ secrets.OPENSHIFT_SERVER }}
          openshift_token: ${{ secrets.OPENSHIFT_TOKEN }}
          namespace: ${{ env.OPENSHIFT_NAMESPACE }}
      
      - name: build-image
        run: |
          oc version
          oc start-build vue-3 --follow
