name: Release Version
on: 
  workflow_dispatch:
  release:
    types: [published]
  # push:
  #   branches: main


jobs:
  build:
    name:  'Run Openshift Build'
    runs-on: ubuntu-latest
    needs: version-bump
    steps:
      - name: Authenticate and set context
        uses: redhat-actions/oc-login@v1
        env:
          OPENSHIFT_USER: jlangy2
          OPENSHIFT_NAMESPACE: jlangy2-dev

        with:
          openshift_server_url: ${{ secrets.OPENSHIFT_SERVER }}
          openshift_token: ${{ secrets.OPENSHIFT_TOKEN }}
          namespace: ${{ env.OPENSHIFT_NAMESPACE }}
      
      - name: build-image
        run: |
          oc version
          oc start-build vue-3 --follow
