name: Lint and test
on: [push]
jobs:
  install:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 14
          cache: 'npm'

      - name: "Install Node Modules"
        run: npm ci
  lint:
    needs: install
    steps:
      - name: 'Lint files'
        run: npm lint