name: Lint and test
on: [push]
jobs:
  lint-and-test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      
      - name: 'Install and Cache Node Modules'
        uses: actions/setup-node@v3
        with:
          node-version: 14
          cache: 'npm'
        run: npm ci

      - name: "Lint files"
        run: npm lint