name: Lint and test
on: [push]
jobs:
  lint-test:
    name: Lint and Test Application
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Cache node modules
        id: cache-npm
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-

      - name: Install dependencies
        run: npm i

      - name: Lint
        run: npm run lint

      - name: Unit Test
        run: npm run test:unit

      - name: End-to-End Test
        run: |
          npm i -g wait-on
          npm run preview --port 4173 & wait-on http://127.0.0.1:4173
          cypress run --e2e
